import type { Lesson } from "./types.ts";

const steps = [
  "Requirements",
  "Scale estimation",
  "API",
  "Data model",
  "High-level architecture",
  "DB",
  "Caching",
  "Queue",
  "Consistency",
  "Failure handling",
  "Observability",
  "Security",
  "Trade-offs",
];

const sheets: Record<string, string[]> = {
  "url-shortener": [
    "Create a short id and redirect. Analytics can lag.",
    "Reads dwarf writes. State a read QPS and a row of a few dozen bytes. Cache the hot ids.",
    "POST /urls returns the short id. GET /{id} redirects 302. Unknown id is 404.",
    "id, long url, owner, created at. The id is random or a base-62 counter.",
    "API, cache, database. A collision retries a new id.",
    "The mapping is the source of truth. A relational table is enough.",
    "Cache-aside on the id. TTL or explicit delete on a rare update.",
    "Clicks are events. The redirect does not write analytics synchronously.",
    "A read can be slightly stale. The create is linearizable on the row.",
    "Cache down: read the database. Redirect still works, slower.",
    "Redirect latency and cache hit ratio.",
    "The owner may delete. The redirect is public. No open redirect to a scheme you do not allow.",
    "A counter id leaks volume. A random id does not and can collide.",
  ],
  "rate-limiter": [
    "Allow or deny a client. The limit is shared across API instances.",
    "One counter read and write per request. The key set is the client set.",
    "The limiter is inside the API, or a filter. 429 with a retry-after when denied.",
    "Key: client id. Value: tokens and a timestamp, or a window count.",
    "Every instance talks to Redis. The decision is one atomic update.",
    "Redis is the store for this counter. It is not the business database.",
    "This is the cache. There is no second cache.",
    "None. The decision is synchronous.",
    "The atomic update is the consistency. A lost Redis is a product choice.",
    "Redis timeout: fail open or fail closed. Say which for this API.",
    "Denied count and Redis latency.",
    "The key is the authenticated client, not a header the caller can forge.",
    "Token bucket is smooth. A fixed window is simpler and allows a burst on the boundary.",
  ],
  notification: [
    "Deliver a message to email, push, or a webhook. At least once, and the user can stand a duplicate more than a loss only if you dedupe.",
    "Fanout is the spike. A popular alert is many devices.",
    "POST /notifications with an idempotency key. Status by id.",
    "Notification, channel, provider id, state.",
    "API writes the row and the outbox. Workers send.",
    "Postgres for state.",
    "Template cache. Not the send state.",
    "Outbox then a worker queue. One queue per channel if a slow provider must not block email.",
    "The provider id makes a retry safe. State moves created, sent, failed.",
    "Provider timeout: retry with the same provider id. Bounce: DLQ.",
    "Send latency, DLQ depth, duplicate rate.",
    "A webhook URL is validated. The body is not an open redirect.",
    "Synchronous send is simpler and falls over when the provider is slow.",
  ],
  "file-storage": [
    "Upload and download an object. Bytes do not sit in the API process.",
    "Large objects, modest metadata QPS.",
    "Start multipart, presign parts, complete, get metadata.",
    "Object, parts, etags, bucket id.",
    "API for metadata. Object store for bytes. Event after commit.",
    "Postgres for metadata.",
    "Metadata cache with eviction on complete and delete.",
    "Outbox for object-created.",
    "Complete is idempotent on the upload id.",
    "Missing part fails complete. Crash after the row commit is the outbox.",
    "Complete errors and bytes used.",
    "Presign expires. No public list.",
    "Proxying bytes is easier to code and wrong at size.",
  ],
  "distributed-cache": [
    "Serve hot bucket metadata with a bound on staleness.",
    "The hot set is small. State the read QPS.",
    "The API does not change. The cache is invisible.",
    "Key bucket id. JSON value. TTL 60 seconds.",
    "Cache-aside in front of Postgres.",
    "Postgres remains the source.",
    "This design is the cache.",
    "None on the read path.",
    "Eventual within the TTL, plus delete on write.",
    "Redis down: read Postgres. Stampede: single-flight.",
    "Hit ratio and fill latency.",
    "Do not cache secrets.",
    "A longer TTL saves the database and lies longer.",
  ],
  chat: [
    "Send a message, receive it, and catch up after a reconnect.",
    "Messages per second per conversation. Sockets are not the storage.",
    "send(conversationId, clientMsgId, body). History by cursor.",
    "Message id, conversation id, body, time. Presence is separate and ephemeral.",
    "A gateway holds sockets. A log stores messages. Fanout reaches online members.",
    "The log is the source. A conversation is a partition.",
    "Presence and the recent fanout. Not the history.",
    "Fanout to online members. The log is durable.",
    "clientMsgId dedupes. Order is per conversation.",
    "Crash after store and before fanout: the client catch-up repairs it.",
    "Send latency and fanout lag.",
    "A member check on send. Encryption is a sentence if asked.",
    "Keeping history only on the gateway loses it on restart.",
  ],
  "news-feed": [
    "Show a home feed. Ranking can be recency in version one.",
    "Follows are uneven. Design for a celebrity.",
    "Post, follow, get feed by cursor.",
    "Post stored once. Inbox rows are ids.",
    "Write the post. A worker fans it out, or the read merges celebrities.",
    "Post table is the source. Inboxes are derived.",
    "The rendered page.",
    "The fanout work.",
    "Eventual within seconds.",
    "A failed fanout retries. A poison post is dead-lettered.",
    "Fanout lag.",
    "A user sees posts they are allowed to see. Block lists are a filter.",
    "Pure push falls over on a celebrity. Hybrid is the trade.",
  ],
  search: [
    "Keyword search over object names and incident notes.",
    "Query rate and index size. Writes are the event rate.",
    "GET /search?q= .",
    "Document id, tokens, source id.",
    "The database emits an event. An indexer updates an inverted index. Queries hit the index, then load the row.",
    "Postgres is the source. The index is derived.",
    "Hot queries.",
    "The index events.",
    "Stale by the indexer lag. Say the lag.",
    "A rebuild from the database exists.",
    "Indexer lag and query latency.",
    "The same authorization as the row. The index must not leak a private incident.",
    "LIKE on the primary table is simpler and dies at size.",
  ],
  payments: [
    "Charge once and keep a history.",
    "Correctness over throughput. State a modest write QPS.",
    "POST /charges with Idempotency-Key. Same key and same body returns the same charge. A different body is 409.",
    "Charge state and ledger lines. Balance is a sum you can rebuild.",
    "API, database, provider call with the same key.",
    "Postgres. The ledger is the source.",
    "None on the write path.",
    "Provider calls can be async after authorization if you split states.",
    "The key and the state machine. Illegal jumps fail.",
    "Provider timeout: retry with the same key. Unknown result: reconcile.",
    "State counts and provider errors.",
    "The key is bound to the authenticated caller. Amounts are integers of minor units.",
    "A single balance column is shorter and unauditable.",
  ],
  "ride-booking": [
    "Match a rider to one nearby driver.",
    "Location writes are hot. Matches are rarer.",
    "Request ride, accept, start, complete.",
    "Trip state. Driver status. Latest location.",
    "Location store, a matcher, a conditional update on the driver.",
    "Trips in Postgres. Locations in a cache or a specialized store.",
    "Latest location only.",
    "Match attempts if the first driver loses the race.",
    "The conditional update is the lock: status was free.",
    "The loser tries the next driver. A matcher crash retries the request id.",
    "Match latency and double-offer count, which must stay zero.",
    "A rider sees their trip. Location retention is short.",
    "A scan for the nearest driver is simpler and races.",
  ],
  "rag-design": [
    "Answer a question about incidents with citations.",
    "Question rate is low. The corpus is the synthetic set.",
    "POST /diagnose. The response includes evidence ids.",
    "Chunks with incident ids. Questions and expected ids for the eval.",
    "Ingest, embed, retrieve, prompt, validate.",
    "Postgres or files are the source. The vector index is derived.",
    "None required at this size.",
    "Ingestion can be a job. The question is synchronous.",
    "Empty retrieval means 'I do not know', not a guess.",
    "Model timeout: error with the request id. Bad JSON: one retry.",
    "Token count, citation hit rate, latency.",
    "Synthetic data only. Retrieved text is untrusted.",
    "A chat box without an eval set is a demo.",
  ],
  "agent-platform": [
    "Run a read-only diagnosis and a gated mutation.",
    "Few concurrent sessions. The cost is tokens and tool calls.",
    "Start a run. Approve a proposal. Read the trace.",
    "Run state, proposal, tool result, trace id.",
    "Orchestrator, allow list, human gate, executor, verifier.",
    "Postgres for proposals. Redis for session state.",
    "Session in Redis.",
    "None on the read path. The mutation is a row, then a call.",
    "A proposal executes once. State jumps are checked.",
    "Tool timeout. Process restart loads the pending row.",
    "Trace per run. Token count. Approval latency.",
    "The executor role is separate. Incident text cannot add a tool.",
    "An ungated tool is faster and is the bug.",
  ],
};

export function checklistLessons(slug: string): Lesson[] | undefined {
  const rows = sheets[slug];
  if (!rows || rows.length !== steps.length) return undefined;
  return steps.map((title, index) => ({ title, body: rows[index] }));
}
